### ISSUE TITLE
6.0 new class issue

### ISSUE THREAD

**Issue by Tsunatus** [bsides/horizoverlay#145] opened 2021-12-07 00:08 UTC
Overlay crashes or becomes invisible due to a uncaught error and module error for reaper and looks like sage as well.

[12/6/2021 4:03:00 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:00 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:01 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:01 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:04 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:04 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:20 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:20 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:32 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:32 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:51 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:51 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:03:57 PM] Info: Horizon Overlay: BrowserConsole: Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'. (Source: , Line: 0)
[12/6/2021 4:05:15 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:15 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:40 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:40 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:46 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:46 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:51 PM] Info: Horizon Overlay: BrowserConsole: Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[12/6/2021 4:05:51 PM] Info: Horizon Overlay: BrowserConsole: Uncaught Error: Cannot find module './rpr.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)

**Comment by ngld** [comment] 2021-12-07 00:19
This is a duplicate of #142 and #144.

**Closed** 2021-12-07 00:32 UTC
