### ISSUE TITLE
DPS not being read properly when parsing alliance

### ISSUE THREAD

**Issue by DatGoose** [bsides/horizoverlay#90] opened 2019-11-09 12:54 UTC
Hello, I setup your overlay last night and I encountered a strange bug where DPS was not pulling from the top 8 like I configured instead it was pulling from somewhere in the middle and would often not make sense the numbers that it was showing when reading DPS from ACT.

Despite me being at over 10k DPS on the hunt, and a few others being significantly higher than me(mind you all of these people are Lv.80) the DPS values being pulled were not accurate at all.

![image](https://user-images.githubusercontent.com/38699928/68528863-bc554200-02bd-11ea-8bb9-8a1e84f149f7.png)

**Comment by bsides** [comment] 2019-11-11 13:29
Hi @DatGoose !

Could you please send me a screenshot or the raw data from ACT as well? The reason for it is just to confirm if the data is being sent wrong or if there's an error in the calculation itself. Right now I doubt it's the calculation since it's being used by a lot of users without a complaint so I'd like to investigate if it's an unusual case.

Also be sure to have checked "Sort type: Number Ascending" like this picture: ![](https://user-images.githubusercontent.com/47320226/68330729-1536a600-0117-11ea-927d-ae876f4b6eae.png)

Thank you!

**Comment by LysLuc** [comment] 2019-11-21 23:04
Static member of mine had the same issue, they have the right settings for it to show everything properly and it works in 8 man, just not in 24man.

Picture below has the Mini Parse, ACT itself, Horizon Overlay and Kagerou.
![unknown](https://user-images.githubusercontent.com/40733794/69384004-6c15b100-0cbb-11ea-8b02-d8950f934846.png)

**Comment by bsides** [comment] 2019-11-22 14:12
Ok Thanks for the report @LysLuc ! I'll be needing some help to sort this thing out as I'm not playing the game anymore. Let's hope someone can give us a hand!

**Comment by CalumDM** [comment] 2019-11-26 18:58
What kind of hand would you need?

The issue has been happening since the new expansion, (July) only occurs in all alliance raids (24 mans), even when set to party, it still has some interference, typically one of the other healers will creep onto the overlay pushing usually the 'Highest DPS' off. I recall quite often seeing healers appear when I did have it set.

![FFXIV ACT settings](https://user-images.githubusercontent.com/48811284/69663720-b9f53500-107e-11ea-9ff7-bdf723effa82.png)

I can take some screenshots/record footage next time I go in, if that would help?

I do really love this overlay which is why I still use it despite this, its really nice and not obtrusive (other horizontals just look a little more clunky and less stylish, plus this reminds me of the formula 1 position bar <3)

**Comment by Keveff** [comment] 2020-04-08 16:33
Hey,

I was wondering if there was a fix for this issue? I really enjoy the layout and look of the overlay and hope to continue using it for 24-man alliance raids.

It is still currently showing the bottom 8 DPS instead of the top and with the update on ACT, I don't have the option of changing the sort type to Ascending (or at least I'm not sure how to on the newer version of ACT).

**Comment by bsides** [comment] 2020-10-01 17:33
It's provably fixed right now, please test and share your thoughts.

**Closed** 2020-10-01 17:32 UTC
Labels: bug

**Comment by ekumlin** [comment] 2020-10-02 01:48
Just did an alliance raid run and confirmed this is now fixed. Thanks!

**Comment by CalumDM** [comment] 2020-10-02 07:59
Same! Thrilled! Thank you very much.
